"""
storage_service.py

Thin wrapper around the MinIO client used as object storage for:
- originally uploaded documents (bucket: settings.MINIO_BUCKET_UPLOADS),
  replacing the old "save to local disk" behaviour in rag_service.py
- generated PDF reports (bucket: settings.MINIO_BUCKET_REPORTS)

This is the ONLY module that talks to MinIO directly; everything else
(rag_service, report_service, routes) goes through the small functions
exposed here so the rest of the app never imports the `minio` SDK.

MinIO is an OPTIONAL runtime dependency: the `minio` package may not be
installed, or the MinIO server it points at may not be running. Neither
case should ever prevent the FastAPI app from starting or break document
ingestion/chat/retrieval — those don't need object storage at all. Only
downloading an original uploaded file and generating/downloading PDF
reports actually require MinIO to be installed and reachable; every
function below raises `StorageUnavailableError` in that case instead of
letting an ImportError/connection error propagate as an unhandled crash,
so callers (rag_service, report_service, routes) can catch it and degrade
gracefully (see `_save_uploaded_file` in rag_service.py).
"""

from __future__ import annotations

import io
import logging
from datetime import timedelta
from typing import Optional

from config import settings

log = logging.getLogger("storage_service")

try:
    from minio import Minio
    from minio.error import S3Error
    _SDK_AVAILABLE = True
except ImportError:
    Minio = None  # type: ignore[assignment,misc]
    S3Error = Exception  # so `except S3Error` below still works when unused
    _SDK_AVAILABLE = False
    log.warning(
        "The 'minio' package is not installed — object storage (original "
        "file downloads, PDF report storage) is disabled. Run "
        "`pip install -r requirements.txt` to enable it; everything else "
        "(upload/chat/retrieval/memory) still works without it."
    )


class StorageUnavailableError(RuntimeError):
    """Raised when object storage is unavailable: the `minio` package isn't
    installed, or the configured MinIO server can't be reached."""


_client: Optional["Minio"] = None
# Separate client used ONLY to build presigned URLs, pointed at
# MINIO_PUBLIC_ENDPOINT instead of MINIO_ENDPOINT — the signature covers
# the Host header, so the URL must be generated by a client already
# configured with the host the browser will actually use;
# string-replacing the hostname in an already-signed URL would invalidate
# the signature. Both clients pass region=MINIO_REGION explicitly so
# neither ever needs a live network call just to sign a URL — the public
# client's configured host (meant for the browser) usually isn't even
# reachable from inside this container.
_public_client: Optional["Minio"] = None

# Buckets are created lazily on first use and cached here so we don't hit
# MinIO's bucket-exists API on every single upload/download call.
_ensured_buckets: set[str] = set()


def get_client() -> "Minio":
    global _client
    if not _SDK_AVAILABLE:
        raise StorageUnavailableError(
            "Object storage is unavailable: the 'minio' package is not installed."
        )
    if _client is None:
        _client = Minio(
            settings.MINIO_ENDPOINT,
            access_key=settings.MINIO_ACCESS_KEY,
            secret_key=settings.MINIO_SECRET_KEY,
            secure=settings.MINIO_SECURE,
            region=settings.MINIO_REGION,
        )
        log.info("MinIO client initialised at %s (secure=%s)", settings.MINIO_ENDPOINT, settings.MINIO_SECURE)
    return _client


def _get_public_client() -> "Minio":
    global _public_client
    if not _SDK_AVAILABLE:
        raise StorageUnavailableError(
            "Object storage is unavailable: the 'minio' package is not installed."
        )
    if _public_client is None:
        _public_client = Minio(
            settings.MINIO_PUBLIC_ENDPOINT,
            access_key=settings.MINIO_ACCESS_KEY,
            secret_key=settings.MINIO_SECRET_KEY,
            secure=settings.MINIO_SECURE,
            region=settings.MINIO_REGION,
        )
    return _public_client


def ensure_bucket(bucket: str) -> None:
    if bucket in _ensured_buckets:
        return
    client = get_client()
    try:
        if not client.bucket_exists(bucket):
            client.make_bucket(bucket)
            log.info("Created MinIO bucket '%s'", bucket)
    except S3Error as e:
        log.error("Could not ensure bucket '%s': %s", bucket, e)
        raise
    _ensured_buckets.add(bucket)


def is_available() -> bool:
    """Best-effort connectivity check, used by the health endpoint."""
    if not _SDK_AVAILABLE:
        return False
    try:
        get_client().list_buckets()
        return True
    except Exception as e:
        log.warning("MinIO not reachable: %s", e)
        return False


def upload_bytes(
    bucket: str,
    object_name: str,
    data: bytes,
    content_type: str = "application/octet-stream",
) -> str:
    """Upload raw bytes to `bucket/object_name`. Returns the object name."""
    ensure_bucket(bucket)
    client = get_client()
    client.put_object(
        bucket,
        object_name,
        data=io.BytesIO(data),
        length=len(data),
        content_type=content_type,
    )
    return object_name


def download_bytes(bucket: str, object_name: str) -> bytes:
    """Download and return the full contents of `bucket/object_name`."""
    client = get_client()
    response = client.get_object(bucket, object_name)
    try:
        return response.read()
    finally:
        response.close()
        response.release_conn()


def object_exists(bucket: str, object_name: str) -> bool:
    client = get_client()
    try:
        client.stat_object(bucket, object_name)
        return True
    except S3Error:
        return False


def delete_object(bucket: str, object_name: str) -> None:
    client = get_client()
    try:
        client.remove_object(bucket, object_name)
    except S3Error as e:
        log.warning("Could not delete '%s/%s': %s", bucket, object_name, e)


def presigned_url(bucket: str, object_name: str, expiry_seconds: Optional[int] = None) -> Optional[str]:
    """Return a temporary, directly-downloadable URL for an object, or
    None if object storage is unavailable/unreachable (the caller can fall
    back to proxying the download through the backend instead)."""
    try:
        client = _get_public_client()
        return client.presigned_get_object(
            bucket,
            object_name,
            expires=timedelta(seconds=expiry_seconds or settings.MINIO_PRESIGNED_EXPIRY),
        )
    except Exception as e:
        log.warning("Could not build presigned URL for '%s/%s': %s", bucket, object_name, e)
        return None
