"""
ocr_engine.py

Runs Tesseract OCR on every processed image generated by
ImageProcessor and stores the results in PageData.
"""

import pytesseract

from .config import Config
from .models import OCRResult, PageData


class TesseractEngine:
    """
    Runs Tesseract OCR on all processed images of a page.
    """

    def __init__(self):
        """
        Initialize Tesseract.
        """

        if Config.TESSERACT_CMD:
            pytesseract.pytesseract.tesseract_cmd = Config.TESSERACT_CMD

    # ======================================================
    # Public Method
    # ======================================================

    def process(self, page: PageData) -> PageData:
        """
        Run OCR on every processed image, trying every configured PSM
        mode for each one. Each (preprocessing method, psm) combination
        produces its own OCRResult, e.g. "otsu_psm6", "otsu_psm3", ...
        """

        # Skip TXT files
        if page.original_image is None:
            return page

        for method_name, image in page.processed_images.items():

            for psm in Config.TESSERACT_PSM_MODES:

                try:
                    text = self._extract_text(image, psm)
                except Exception:
                    continue

                if not text:
                    continue

                confidence = self._calculate_confidence(image, psm)

                key = f"{method_name}_psm{psm}"

                page.ocr_results[key] = OCRResult(
                    text=text,
                    confidence=confidence,
                    preprocessing_method=method_name
                )

        # Fallback: if every method/psm combination came back empty,
        # fall back to a single plain OCR pass on the original image.
        if not page.ocr_results:

            try:
                text = self._extract_text(
                    page.original_image,
                    Config.TESSERACT_PSM
                )
            except Exception:
                text = ""

            page.ocr_results["fallback"] = OCRResult(
                text=text,
                confidence=0.0,
                preprocessing_method="fallback"
            )

        return page

    # ======================================================
    # Private Methods
    # ======================================================

    def _extract_text(self, image, psm: int) -> str:
        """
        Extract text using Tesseract at the given PSM mode.
        Falls back to eng if the configured language pack is missing.
        """
        config = Config.tesseract_config_for(psm)
        try:
            text = pytesseract.image_to_string(
                image,
                lang=Config.OCR_LANGUAGE,
                config=config,
            )
        except Exception:
            text = pytesseract.image_to_string(
                image,
                lang="eng",
                config=config,
            )

        return text.strip()

    def _calculate_confidence(self, image, psm: int) -> float:
        """
        Calculate the average OCR confidence at the given PSM mode.
        Falls back to eng if the configured language pack is missing.
        """
        config = Config.tesseract_config_for(psm)
        try:
            data = pytesseract.image_to_data(
                image,
                lang=Config.OCR_LANGUAGE,
                config=config,
                output_type=pytesseract.Output.DICT,
            )
        except Exception:
            data = pytesseract.image_to_data(
                image,
                lang="eng",
                config=config,
                output_type=pytesseract.Output.DICT,
            )

        confidences = []

        for conf in data["conf"]:

            try:
                value = float(conf)

                if value >= 0:
                    confidences.append(value)

            except ValueError:
                continue

        if not confidences:
            return 0.0

        return sum(confidences) / len(confidences)